### ISSUE TITLE
INFOPLIST_FILE path is not work

### ISSUE THREAD

**Issue by dangthaison91** [e-sites/Natrium#11]
I have more than one build target, therefore the project will have 2 or more `Infor.plist` files.

But actual, `infoPlistPath` will be like: `DemoProject/$(SRCROOT)/Info.plist`. So Natrium cannot generate the Config.

I also define plist file path in `.natrium.yml` but seem that they are not to be used or maybe I using it in wrong way
```yml
plists:
  "DemoProject/Info.plist":
        CFBundleDisplayName:
            Dev: Dev Demo
            Staging: Staging Demo
            Production: Demo

    "DemoProject/Debug-Info.plist":
        CFBundleDisplayName:
            Dev: Dev Demo
            Staging: Staging Demo
            Production: Demo
```

```swift
❌  Cannot find Optional("//Volumes/DATA/DemoProject/$(SRCROOT)/DemoProject/Info.plist")

```

**Comment by basvankuijck** [comment]
Thas has probably to do with the fact that you use {{$(SRCROOT)}} in your {{INFOPLIST_FILE}} path.

Could you remove {{$(SRCROOT)}} from your {{INFOPLIST_FILE}} in your build settings? And check again.

I'll try to fix it in a next version

**Comment by basvankuijck** [comment]
Besides that this would be a better setup:

```yaml
target_specific: 
  Target1: 
    plists: 
      DemoProject/Info.plist: 
        CFBundleDisplayName: 
          Dev: "Dev Demo"
          Production: Demo
          Staging: "Staging Demo"
  Target2: 
    plists: 
      DemoProject/Debug-Info.plist: 
        CFBundleDisplayName: 
          Dev: "Dev Demo"
          Production: Demo
          Staging: "Staging Demo"
```

Else everytime you run either of the two targets the plist file for the other target will be changed
