### ISSUE TITLE
Environment not generate as String

### ISSUE THREAD

**Issue by dangthaison91** [e-sites/Natrium#18]
I have some environment variables for CI but Natrium not generate them as Swift String.

**.env file:**
```yml
  API_DOMAIN = 'https://api.domain.com'
```

**natrium:**
```yml
  variables:
  domain:
    Staging: "api.staging.id.vin"
    Production: "#env(API_DOMAIN)"
```

**Natrium.swift:**

```swift
class Natrium {

    enum Environment: String {
        case staging = "Staging"
        case production = "Production"
    }

    enum Configuration: String {
        case debug = "Debug"
        case release = "Release"
    }

    class Config {
        static let domain: String = https://api.domain.com
    }
}
```

It should be Swift String with double quote "":
```swift
class Natrium {
    class Config {
        static let domain: String = "https://api.domain.com"
    }
}
```
