### ISSUE TITLE
Natrium should remove all xcconfig files before generate

### ISSUE THREAD

**Issue by dangthaison91** [e-sites/Natrium#20]
When using Natrium, many times it implicitly failed at local but build still success cause xcconfig files already generated before. This often takes time to check why CI build failed and notice to check Natrium's log.

I'm not sure if once Natrium fails can it make Pre-Action fail the following Build will be failed? If not we can remove all xcconfig files before generating a new one.

**Comment by basvankuijck** [comment]
Pre-actions unfortunately cannot stop or fail the build itself.

What might improve your CI builds is to call natrium from your build pipeline itself.

For example (in `.travis.yml`):
```yaml
language: objective-c
osx_image: xcode10

script:
  - ./natrium -c Release -e Production -t App -p $TRAVIS_BUILD_DIR
  - xcodebuild ... etc

```
