### ISSUE TITLE
xcassets

### ISSUE THREAD

**Issue by philosopherdog** [e-sites/Natrium#21]
Is it possible to configure the inclusion and exclusion of different xcassets depending on environment or configuration?

**Comment by basvankuijck** [comment]
What you could do is the following:

Create (for instance) a PDF asset and place it in a folder:
- `MyApp/Resources/Assets.xcassets/MyImage.imageset/MyImage.pdf`

And make (for instance) environment specific instances in:
- `Environments/Staging/MyImage.pdf`
- `Environments/Production/MyImage.pdf`

Then use the `files` settings in your `.natrium.yml`:

```yaml

files:
  "MyApp/Resources/Assets.xcassets/MyImage.imageset/MyImage.pdf":
    Staging: "Environments/Staging/MyImage.pdf"
    Production: "Environments/Production/MyImage.pdf"
```

That way `Environments/Staging/MyImage.pdf` will be copied (and replace) `MyApp/Resources/Assets.xcassets/MyImage.imageset/MyImage.pdf` in the pre-build step for your Staging environment
