### ISSUE TITLE
Config different Capabilities based on environment

### ISSUE THREAD

**Issue by vinhlk** [e-sites/Natrium#24]
Hi is there a way to config Different Capabilities base on environment (Dev, Stagging, Production) (in my case is `AppGroup`) ?

Seem we should modify

`plists:
    "NatriumExampleProject/Info.plist":
        CFBundleDisplayName:
            Staging: App_staging
            Production: App
    "NatriumExampleProject/App.entitlements":
        "aps-environment":
            "*":
                Debug: "development"
                Release: "production"`

But what is the config for other capabilities? (`AppGroup` for example)?

**Comment by basvankuijck** [comment]
You could use xcconfig variables in your entitlements file, for instance:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>$(APPGROUP1)</string>
		<string>$(APPGROUP2)</string>
	</array>
</dict>
</plist>
```

and then use this in `.natrium.yml`
```yaml
xcconfig:
    APPGROUP1: "com.app.group1"
    APPGROUP2: "com.app.group2"
```

or create different entitlement files per configuration / environment and use the `files` setting in your `.natrium.yml` file

**Comment by vinhlk** [comment]
Thanks. How about extension entitlement? (`PushNotificationExtension.entitlements`) (in extension we also have entitlement)

**Comment by basvankuijck** [comment]
@vinhlk: Yes, works the same way

**Comment by vinhlk** [comment]
I have tried NotificationExtension. the 1st option xcconfig does not seem to work. (Also created scheme for pushnotification-dev, pushnotification-staging...)

**Comment by basvankuijck** [comment]
Another approach would be to use the `files` setting in your `.natrium.yml` file:

```yaml

files:
    Path/To/NotificationExtensions.entitlements:
        Staging: Path/To/NotificationExtensions-staging.entitlements:
        Staging: Path/To/NotificationExtensions-production.entitlements:
```

The only thing you need to do is create 2 seperate entitlements files for each environment
