### ISSUE TITLE
plists in target specific

### ISSUE THREAD

**Issue by mapo80** [e-sites/Natrium#3]
I think there's a bug with target specific.

If I use this configuration:

```
target_specific:
    target_name:
        plists:
            "plist_path":
                CFBundleDisplayName:
                    Mock: XXXX
                    Dev: BG dev
        variables:
            var_1: "var_1"
            var_2: "var_2"
```

I can't set CFBundleDisplayName, in fact log contains this:
```
03/07/2018, 19:45:05 -   [target_specific:target_name]
03/07/2018, 19:45:05 -     variables
03/07/2018, 19:45:05 -       var_1 = var_1
03/07/2018, 19:45:05 -       var_2 = var_2
03/07/2018, 19:45:05 -       plists
03/07/2018, 19:45:05 -         -empty-
```

Plists is empty, how to fix this?

Thanks.
