### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by eldare** [e-sites/Natrium#31]
I would like to create an array of `String`s as my configuration variable. But it doesn't seem to work.

Am I doing something wrong, or arrays not supported?
I've tried the following, it fails to create `Natrium.swift`
```
variables:
    listOfStuff: ["aaa", "bbb"]
    anotherList:
        - abc
        - efg
```

Thank you.
