### ISSUE TITLE
Bool and Int values are not overridden per target

### ISSUE THREAD

**Issue by eldarhealthyio** [e-sites/Natrium#4]
It seems that non String values are not overridden correctly

Simplified example:
```
variables:
    message: "hello"
    isDoSomething: false
    someNumber: 0

target_specific:
    MyTarget:
        variables:
            message: "yo"
            isDoSomething: true
            someNumber: 1
```

This produces:
```
open static let message: String = "yo"
open static let isDoSomething: Bool = false
open static let someNumber: Int = 0
```

Notice the string is overridden correctly, but the bool and int were not.

Natrium version 5.7.0
Installed with Carthage

Thank you
