### ISSUE TITLE
PRODUCT_BUNDLE_IDENTIFIER cannot be specify

### ISSUE THREAD

**Issue by waltcow** [e-sites/Natrium#6]
.natrium.config file below

```yaml
xcconfig:
    PRODUCT_BUNDLE_IDENTIFIER:
        Staging: com.my.app.staging
        Production: com.my.app.production
```

when i print `bundleIdentifier` in the runtime

```
print("bundle identifier: \(Bundle.main.bundleIdentifier!)")
```
every mode is print the same bundleIdentifier

Anyone help me to debug this issue?
