### ISSUE TITLE
How can I specify array of dictionaries in plists value? 

### ISSUE THREAD

**Issue by dkalachov** [e-sites/Natrium#9]
```yml
plists:
    "Resources/Info.plist":
        CFBundleURLTypes:
            - CFBundleURLSchemes:
                - "#{FacebookUrlScheme}"
              CFBundleTypeRole: "Editor"
            - CFBundleURLSchemes:
                - "#{GoogleUrlScheme}"
              CFBundleTypeRole: "Editor"
```

This code results in empty array. Am I doing something wrong? 

Thanks.

**Comment by basvankuijck** [comment]
This is currently not possible.
Because Natrium expects the following structure:

```yaml
plists:
    "NatriumExampleProject/Info.plist":
        CFBundleDisplayName:
            Staging: App_staging
            Production: App
```

I would suggest doing the following:
Make `xcconfig` variables in `.natrium.yml`:
```yaml
xcconfig:
    FACEBOOK_URL_SCHEME: "#{FacebookUrlScheme}"
    GOOGLE_URL_SCHEME: "#{GoogleUrlScheme}"
```

And use them in your `Info.plist` file:
`$(FACEBOOK_URL_SCHEME)` and `$(GOOGLE_URL_SCHEME)`
